name: Build and publish Docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: read
  packages: read

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Make some extra space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          [[ -n "${AGENT_TOOLSDIRECTORY:-}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /opt/microsoft
          sudo rm -rf /opt/google
          sudo rm -rf /usr/lib/firefox
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/julia*
          docker image prune --all

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: vicoslab/slaif-ai-vision-toolbox
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/vicoslab/toolbox.git#${{ github.ref_name }}
          push: true
          build-args: |
            REF=${{ github.ref_name }}
            TOOLBOX_BRAND_NAME_LONG=SLAIF AI Vision Toolbox by ViCoS
            TOOLBOX_BRAND_NAME_SHORT=SLAIF Toolbox
          build-contexts: |
            branding=.
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
